# From https://gitlab.com/gitlab-org/gitlab-ce/blob/v12.2.1/lib/gitlab/ci/templates/Auto-DevOps.gitlab-ci.yml
# Modifications:
# * Adds before_script that sets up ssh keys from env variables before each job. Needed so the jobs can pull private gitlab repos.
# * don't use default test stage. Use one that runs `npm test` inside the docker image built by the build stage.
#   The default one uses 'herokuish test' which takes a long time and has no way to configure for our package.json git:// url deps that need to use ssh keys to authorize

image: alpine:latest

variables:
  # These are from the auto devops template
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "" # https://gitlab.com/gitlab-org/gitlab-runner/issues/4501
  POSTGRES_DB: $CI_ENVIRONMENT_SLUG
  POSTGRES_ENABLED: "true"
  POSTGRES_PASSWORD: testing-password
  POSTGRES_USER: user
  # POSTGRES_VERSION: 9.6.2
  ROLLOUT_RESOURCE_TYPE: deployment

  # These are custom or overrides
  K8S_SECRET_CI_ENVIRONMENT_NAME: ${CI_ENVIRONMENT_NAME}
  K8S_SECRET_CI_ENVIRONMENT_SLUG: ${CI_ENVIRONMENT_SLUG}
  K8S_SECRET_CONFIG_NAME: ${CI_ENVIRONMENT_SLUG}
  POSTGRES_VERSION: "11.5"

before_script:
- '[ -z "$TRACE" ] || set -x'

stages:
  - build
  - test
  - deploy  # dummy stage to follow the template guidelines
  - review
  - dast
  - staging
  - canary
  - production
  - incremental rollout 10%
  - incremental rollout 25%
  - incremental rollout 50%
  - incremental rollout 100%
  - performance
  - cleanup

include:
- template: Jobs/Build.gitlab-ci.yml # https://gitlab.com/gitlab-org/gitlab-ce/blob/master/lib/gitlab/ci/templates/Jobs/Build.gitlab-ci.yml
# - /etc/gitlab-ci/autodevops-docker-test.gitlab-ci.yml
- template: Jobs/Test.gitlab-ci.yml # https://gitlab.com/gitlab-org/gitlab-ce/blob/master/lib/gitlab/ci/templates/Jobs/Test.gitlab-ci.yml
- template: Jobs/Code-Quality.gitlab-ci.yml # https://gitlab.com/gitlab-org/gitlab-ce/blob/master/lib/gitlab/ci/templates/Jobs/Code-Quality.gitlab-ci.yml
- template: Jobs/Deploy.gitlab-ci.yml # https://gitlab.com/gitlab-org/gitlab-ce/blob/master/lib/gitlab/ci/templates/Jobs/Deploy.gitlab-ci.yml
- template: Jobs/Browser-Performance-Testing.gitlab-ci.yml # https://gitlab.com/gitlab-org/gitlab-ce/blob/master/lib/gitlab/ci/templates/Jobs/Browser-Performance-Testing.gitlab-ci.yml
- template: Security/DAST.gitlab-ci.yml # https://gitlab.com/gitlab-org/gitlab-ce/blob/master/lib/gitlab/ci/templates/Security/DAST.gitlab-ci.yml
- template: Security/Container-Scanning.gitlab-ci.yml # https://gitlab.com/gitlab-org/gitlab-ce/blob/master/lib/gitlab/ci/templates/Security/Container-Scanning.gitlab-ci.yml
- template: Security/Dependency-Scanning.gitlab-ci.yml # https://gitlab.com/gitlab-org/gitlab-ce/blob/master/lib/gitlab/ci/templates/Security/Dependency-Scanning.gitlab-ci.yml
- template: Security/License-Management.gitlab-ci.yml # https://gitlab.com/gitlab-org/gitlab-ce/blob/master/lib/gitlab/ci/templates/Security/License-Management.gitlab-ci.yml
- template: Security/SAST.gitlab-ci.yml # https://gitlab.com/gitlab-org/gitlab-ce/blob/master/lib/gitlab/ci/templates/Security/SAST.gitlab-ci.yml

build:
  variables:
    # buildkit is required to use --ssh default arg,
    # which is useful because then docker build will pass through ssh-agent to the builder
    # so that `npm install` can use ssh to authenticate to find private npm repos
    DOCKER_BUILDKIT: "1"
    AUTO_DEVOPS_BUILD_IMAGE_EXTRA_ARGS: "--build-arg NPM_CONFIG_REGISTRY --build-arg NPM_CONFIG_LOGLEVEL"

# Override DAST job to exclude master branch
dast:
  except:
    refs:
      - master

# This job only exists so other ones can 'needs' it.
# (needs: [] is not allowed)
"pipeline_started":
  stage: build
  script:
  - echo pipeline_started

code_quality:
  needs: [pipeline_started]

production:
  variables:
    CI_ENVIRONMENT_URL: ${PRODUCTION_URL}
