export declare const sharedWebSockets: {};
export declare const DEFAULT_OPTIONS: {};
export declare const READY_STATE_CONNECTING = 0;
export declare const READY_STATE_OPEN = 1;
export declare const READY_STATE_CLOSING = 2;
export declare const READY_STATE_CLOSED = 3;
export declare const SOCKET_IO_PING_INTERVAL: number;
export declare const SOCKET_IO_PATH = "/socket.io/?EIO=3&transport=websocket";
export declare const SOCKET_IO_PING_CODE = 2;
export declare const RETRY_LIMIT = 2;
