test:
  stage: test
  image: docker:18-git
  services:
  - docker:18-dind
  script:
    - |
      if [[ -n "$CI_REGISTRY_USER" ]]; then
        echo "Logging to GitLab Container Registry with CI credentials..."
        docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
        echo ""
      fi
    - |
      if ! docker info &>/dev/null; then
        if [ -z "$DOCKER_HOST" -a "$KUBERNETES_PORT" ]; then
          export DOCKER_HOST='tcp://localhost:2375'
        fi
      fi
    - export CI_APPLICATION_REPOSITORY=$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG
    - export CI_APPLICATION_TAG=$CI_COMMIT_SHA
    - echo '$CI_APPLICATION_REPOSITORY:$CI_APPLICATION_TAG'="$CI_APPLICATION_REPOSITORY:$CI_APPLICATION_TAG"
    - docker run -e CI "$CI_APPLICATION_REPOSITORY:$CI_APPLICATION_TAG" sh -c 'npm test'
  only:
    - branches
  except:
    variables:
      - $TEST_DISABLED
