name: deploy prod
on:
  workflow_dispatch:
    inputs:
      pulumi_command:
        description: 'pulumi command'
        required: true
        type: string
        default: up
      pulumi_stack_name:
        description: 'pulumi stack name'
        required: true
        type: choice
        options:
        - prod
        default: prod
      environment_url:
        description: environment url
        type: string
        required: false
        default: https://activitypub.com
jobs:
  update:
    name: pulumi up --stack ${{ inputs.pulumi_stack_name }}
    environment:
      name: ${{ inputs.pulumi_stack_name }}
      url: ${{ inputs.environment_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - run: npm install
      - uses: pulumi/actions@v3
        with:
          command: ${{ inputs.pulumi_command }}
          stack-name: ${{ inputs.pulumi_stack_name }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
