name: on delete branch, pulumi destroy
on:
  - delete
jobs:
  pulumi-destroy:
    name: pulumi destroy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Extract env name from branch name
        shell: bash
        run: echo "##[set-output name=environment;]$(echo "$GITHUB_REF" | sed 's|/|-|g')"
        id: extract_environment
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - run: npm install
      - uses: pulumi/actions@35f51396579b3b55f0741396cff6904ec35d3f09
        with:
          command: destroy
          stack-name: ${{ steps.extract_environment.outputs.environment }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
